name: Terraform test
on:
  push:
    branches-ignore:
      - main
    paths:
      - '**.tf'
      - .github/workflows/terraform-test.yaml
      - .github/tfnotify.yaml
defaults:
  run:
    shell: bash
jobs:
  test:
    name: Terraform test
    runs-on: ubuntu-latest
    env:
      TF_VAR_rds_user: ${{ secrets.RDS_USER }}
      TF_VAR_rds_password: ${{ secrets.RDS_PASSWORD }}
      TF_VAR_rds_secret: ${{ secrets.RDS_SECRET }}
      TF_VAR_user_db_dsn: ${{ secrets.USER_DB_DSN }}
      TF_VAR_account_db_dsn: ${{ secrets.ACCOUNT_DB_DSN }}
      TF_VAR_todo_db_dsn: ${{ secrets.TODO_DB_DSN }}
      TF_VAR_argocd_secret: ${{ secrets.ARGOCD_SECRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Install dependent packages
        run: |
          mkdir -p /usr/local/bin
          wget https://github.com/mercari/tfnotify/releases/download/v0.7.0/tfnotify_linux_amd64.tar.gz -P /tmp
          tar zxvf /tmp/tfnotify_linux_amd64.tar.gz -C /tmp
          sudo mv /tmp/tfnotify /usr/local/bin/tfnotify

      - name: Terraform format
        run: terraform fmt -recursive -check

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform plan
        run: |
          terraform plan -no-color | \
          tfnotify --config .github/tfnotify.yaml plan --message "Planned Date: $(TZ=UTC-9:00 date +"%Y/%m/%d %H:%M:%S")"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
